#
# acpphint's makefile.RPi5-8192MiB-threads_4-LP64-FreeBSD_main_64bit-clang++_19_O3lto-libc++
# example (as of requiring C++23 or later)
#
#  Copyright (c) 2015-2024 Mark Millard
#  Copyright (C) 1994 by Iowa State University Research Foundation, Inc.
#
#  Note: Any acpphint*.{h,cpp} code or makefile code
#        that is insufficiently original comes under
#        the Iowa State University Research Foundation,
#        Inc. copyright.
#
#        This does not apply to cpp_*.{h,cpp} or
#        sys_*.{h,cpp} code: that is strictly mine.
#
#  This program is free software; you can redistribute it
#  and/or modify it under the terms of the GNU General
#  version 2 Public License as published by the Free
#  Software Foundation.
#
#  This program is distributed in the hope that it will
#  be useful, but WITHOUT ANY WARRANTY; without even the
#  implied warranty of MERCHANTABILITY or FITNESS FOR A
#  PARTICULAR PURPOSE.  See the GNU General Public
#  License for more details.
#
#  You should have received a copy of the GNU General
#  Public License version 2 along with this program; if
#  not, write to:
#
#  Free Software Foundation, Inc.
#  51 Franklin Street, Fifth Floor,
#  Boston, MA  02110-1301, USA.
#
.POSIX:
.SUFFIXES:

THE_MAKEFILE= makefile.RPi5-8192MiB-threads_4-LP64-FreeBSD_main_64bit-clang++_19_O3lto-libc++

#
# acpphint's makefile.*'s are very tailored to my use but may be
# used to see how to build the investigative programs and the
# benchmark program and what they in turn require.
#
# Before including makefile.common_part :
# Adjust CXXLIB, CXX, OPT, CPULOCKDOWN_OPT, LDCXX, COMPILER_DESC, 
# LIBRARY_DESC, COMPUTER, RAM, THREADS, CPP_DATA_MODEL, OS,
# and SUFFIX as appropriate.
#
# The major targets are: build gather-info gather-NOPREFER-info
# But acpphint-run just runs the basic acpphint benchmarks, but no
# cpuset, taskset, etc. used.
# But acpphint-NOPREFER-run just runs the NOPREFER accphint
# benchmarks, cpuset, taskset, etc. possibly used.
#
# The makefile.*'s are not set up for cross-build use.
#
# The naming used does require (relative to POSIX):
# "allow other characters in target names as extensions"
#

#
# This file presumes FreeBSD c++ is clang++ 19 based or later.
#

CXXLIB=
CXX=            c++ -v -std=c++23 -Wpedantic -Wall -Wextra
#CXX+=           -stdlib=libc++
CXX+=           -fexperimental-library
#CXX+=           -DDSIZE_ALL_ISIZE_ALL
#CXX+=           -m32 -target armv7-unknown-freebsd15.0-gnueabihf
OPT=            -O3
LTO_STYLE=      -flto
OPT+=           ${LTO_STYLE}
OPT+=           -mcpu=cortex-a76
#OPT+=           -mcpu=cortex-a7
CPULOCKDOWN_OPT=
#CPULOCKDOWN_OPT=        -DWANT_CPU_LOCKDOWN
# Note for FreeBSD: WANT_NUMA_TOO is implicit/automatic; not so for Linux
#CPULOCKDOWN_OPT+=       -DWANT_NUMA_TOO
LDCXX+=         -fuse-ld=lld ${LTO_STYLE}
#LDCXX+=         -Wl,-rpath=/usr/local/lib/gccVERSION
# For Linux NUMA use:
#LDCXX+=         -lnuma

COMPILER_DESC=      clang++_19_O3lto
LIBRARY_DESC=       libc++
ABI_VARIANT=
#ABI_VARIANT=        -${CPP_DATA_MODEL}
COMPILER_LIBRARY=   ${COMPILER_DESC}-${LIBRARY_DESC}${ABI_VARIANT}

COMPUTER=               RPi5
RAM=                    8192MiB
THREADS=                threads_4
CPP_DATA_MODEL=         LP64
OS=                     FreeBSD_main_n273201_e4ac0183a1a8_64bit
#CPP_DATA_MODEL=         ILP32
SUFFIX=
#SUFFIX=                 -cpulockdown
ACPPHINT_FILENAME_INFO= ${COMPUTER}-${RAM}-${THREADS}-${CPP_DATA_MODEL}-${OS}-${COMPILER_LIBRARY}${SUFFIX}
#
# Note: The "threads_4" is what the hardware has for
# HW threads --or as presented by the likes of HyperV.
# acpphint will also add using_N_threads to file names
# recording benchmark results.

include makefile.common_part

#
#  Support some special NOPREFER-related information gathering:
#
gather-NOPREFER-info: \
		cpp_clockinfo_main-run \
		acpphint_kernelsurveyors_main-run \
		acpphint_kernelsamplers_main-run \
		acpphint-NOPREFER-run

acpphint-NOPREFER-run:
	cd .. && cpuset -l1     ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_1.txt"       1
	cd .. && cpuset -l2     ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_2.txt"       1
	cd .. && cpuset -l3     ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_3.txt"       1
	cd .. && cpuset -l1,2   ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_1_2.txt"     2
	cd .. && cpuset -l1,3   ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_1_3.txt"     2
	cd .. && cpuset -l2,3   ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_2_3.txt"     2
	cd .. && cpuset -l1-3   ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_1_2_3.txt"   3
	cd .. && cpuset -l0     ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0.txt"       1
	cd .. && cpuset -l0,1   ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_1.txt"     2
	cd .. && cpuset -l0,2   ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_2.txt"     2
	cd .. && cpuset -l0,3   ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_3.txt"     2
	cd .. && cpuset -l0,1,2 ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_1_2.txt"   3
	cd .. && cpuset -l0,1,3 ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_1_3.txt"   3
	cd .. && cpuset -l0,2,3 ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_2_3.txt"   3
	cd .. && cpuset -l0-3   ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_1_2_3.txt" 4
	cd .. && ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} ".txt" 1 4
