#
# acpphint's makefile.MacchDblShot-16384MiB-threads_4-LP64-ubuntu_21_04_64bit-g++_11_O3lto-libstdc++
# example (as of requiring C++20 or later)
#
#  Copyright (c) 2015-2021 Mark Millard
#  Copyright (C) 1994 by Iowa State University Research Foundation, Inc.
#
#  Note: Any acpphint*.{h,cpp} code or makefile code
#        that is insufficiently original comes under
#        the Iowa State University Research Foundation,
#        Inc. copyright.
#
#        This does not apply to cpp_*.{h,cpp} or
#        sys_*.{h,cpp} code: that is strictly mine.
#
#  This program is free software; you can redistribute it
#  and/or modify it under the terms of the GNU General
#  version 2 Public License as published by the Free
#  Software Foundation.
#
#  This program is distributed in the hope that it will
#  be useful, but WITHOUT ANY WARRANTY; without even the
#  implied warranty of MERCHANTABILITY or FITNESS FOR A
#  PARTICULAR PURPOSE.  See the GNU General Public
#  License for more details.
#
#  You should have received a copy of the GNU General
#  Public License version 2 along with this program; if
#  not, write to:
#
#  Free Software Foundation, Inc.
#  51 Franklin Street, Fifth Floor,
#  Boston, MA  02110-1301, USA.
#
.POSIX:
.SUFFIXES:

THE_MAKEFILE= makefile.MacchDblShot-16384MiB-threads_4-LP64-ubuntu_21_04_64bit-g++_11_O3lto-libstdc++

#
# acpphint's makefile.*'s are very tailored to my use but may be
# used to see how to build the investigative programs and the
# benchmark program and what they in turn require.
#
# Before including makefile.common_part :
# Adjust CXXLIB, CXX, OPT, CPULOCKDOWN_OPT, LDCXX, COMPILER_DESC, 
# LIBRARY_DESC, COMPUTER, RAM, THREADS, CPP_DATA_MODEL, OS,
# and SUFFIX as appropriate.
#
# The major targets are: build gather-info gather-NOPREFER-info
# But acpphint-run just runs the basic acpphint benchmarks, but no cpuset, taskset, etc. used.
# But gather-NOPREFER-run just runs the NOPREFER accphint benchmarks, cpuset, taskset, etc. used.
#
# The makefile.*'s are not set up for cross-build use.
#
# The naming used does require (relative to POSIX):
# "allow other characters in target names as extensions"
#

#
# This file presumes ubuntu has g++ v11 installed as g++-11 and has make.
#

CXXLIB=
CXX=            g++-11 -v -std=c++20 -Wpedantic -Wall -Wextra
#CXX+=           -Wno-psabi -nostdinc -nostdinc++ -I/usr/include/c++/v1 -I/usr/include
#CXX+=           -DDSIZE_ALL_ISIZE_ALL
OPT=            -O3 -mcpu=cortex-a72 -flto
#OPT+=           -mno-outline-atomics
CPULOCKDOWN_OPT=
#CPULOCKDOWN_OPT=        -DWANT_CPU_LOCKDOWN
# Not used for FreeBSD but used for Linux:
#CPULOCKDOWN_OPT+=       -DSMT_FACTOR=1u
# Note for FreeBSD: WANT_NUMA_TOO is implicit/automatic; not so for Linux
#CPULOCKDOWN_OPT+=       -DWANT_NUMA_TOO
# The below is for other_src_used/sys_cpubinding_lgplv2_1_okay.cpp that I do not
# distribute (but I proved could be implemented on a Linux):
#CPULOCKDOWN_OPT+=       -DLGPLv2_1_OKAY
#LDCXX=          -nodefaultlibs -lc++ -lcxxrt -lthr -lm -lc -lgcc_s
#LDCXX+=         -Wl,-rpath=/usr/local/lib/gcc11
# For Linux NUMA use:
#LDCXX+=         -lnuma

COMPILER_DESC=      g++_11_O3lto
LIBRARY_DESC=       libstdc++
COMPILER_LIBRARY=   ${COMPILER_DESC}-${LIBRARY_DESC}

COMPUTER=               MacchDblShot
RAM=                    16384MiB
THREADS=                threads_4
CPP_DATA_MODEL=         LP64
OS=                     ubuntu_21_04_64bit
SUFFIX=
#SUFFIX=                 -cpulockdown
ACPPHINT_FILENAME_INFO= ${COMPUTER}-${RAM}-${THREADS}-${CPP_DATA_MODEL}-${OS}-${COMPILER_LIBRARY}${SUFFIX}
#
# Note: The "threads_4" is what the hardware has for
# HW threads --or as presented by the likes of HyperV.
# acpphint will also add using_N_threads to file names
# recording benchmark results.

include makefile.common_part

#
#  Support some special NOPREFER-related information gathering:
#
gather-NOPREFER-info: \
		cpp_clockinfo_main-run \
		acpphint_kernelsurveyors_main-run \
		acpphint_kernelsamplers_main-run \
		acpphint-NOPREFER-run

acpphint-NOPREFER-run:
	cd .. && taskset -c 1     ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_1.txt"       1
	cd .. && taskset -c 2     ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_2.txt"       1
	cd .. && taskset -c 3     ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_3.txt"       1
	cd .. && taskset -c 1,2   ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_1_2.txt"     2
	cd .. && taskset -c 1,3   ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_1_3.txt"     2
	cd .. && taskset -c 2,3   ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_2_3.txt"     2
	cd .. && taskset -c 1-3   ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_1_2_3.txt"   3
	cd .. && taskset -c 0     ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0.txt"       1
	cd .. && taskset -c 0,1   ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_1.txt"     2
	cd .. && taskset -c 0,2   ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_2.txt"     2
	cd .. && taskset -c 0,3   ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_3.txt"     2
	cd .. && taskset -c 0,1,2 ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_1_2.txt"   3
	cd .. && taskset -c 0,1,3 ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_1_3.txt"   3
	cd .. && taskset -c 0,2,3 ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_2_3.txt"   3
