#
# acpphint's makefile.7950X3D-98304MiB-threads_32-LP64-FreeBSD_main_64bit-clang++_17_O3lto-libc++
# example (as of requiring C++20 or later)
#
#  Copyright (c) 2015-2023 Mark Millard
#  Copyright (C) 1994 by Iowa State University Research Foundation, Inc.
#
#  Note: Any acpphint*.{h,cpp} code or makefile code
#        that is insufficiently original comes under
#        the Iowa State University Research Foundation,
#        Inc. copyright.
#
#        This does not apply to cpp_*.{h,cpp} or
#        sys_*.{h,cpp} code: that is strictly mine.
#
#  This program is free software; you can redistribute it
#  and/or modify it under the terms of the GNU General
#  version 2 Public License as published by the Free
#  Software Foundation.
#
#  This program is distributed in the hope that it will
#  be useful, but WITHOUT ANY WARRANTY; without even the
#  implied warranty of MERCHANTABILITY or FITNESS FOR A
#  PARTICULAR PURPOSE.  See the GNU General Public
#  License for more details.
#
#  You should have received a copy of the GNU General
#  Public License version 2 along with this program; if
#  not, write to:
#
#  Free Software Foundation, Inc.
#  51 Franklin Street, Fifth Floor,
#  Boston, MA  02110-1301, USA.
#
.POSIX:
.SUFFIXES:

THE_MAKEFILE= makefile.7950X3D-98304MiB-threads_32-LP64-FreeBSD_main_64bit-clang++_17_O3lto-libc++

#
# acpphint's makefile.*'s are very tailored to my use but may be
# used to see how to build the investigative programs and the
# benchmark program and what they in turn require.
#
# Before including makefile.common_part :
# Adjust CXXLIB, CXX, OPT, CPULOCKDOWN_OPT, LDCXX, COMPILER_DESC, 
# LIBRARY_DESC, COMPUTER, RAM, THREADS, CPP_DATA_MODEL, OS,
# and SUFFIX as appropriate.
#
# The major targets are: build gather-info gather-NOPREFER-info gather-NUMA-info
# But acpphint-run just runs the basic acpphint benchmarks, but no
# cpuset, taskset, etc. used.
# But acpphint-NOPREFER-run just runs the NOPREFER accphint
# benchmarks, cpuset, taskset, etc. possibly used.
# But acpphint-NUMA-run runs the NUMA preferenced accphint
# benchmarks, cpuset used.
#
# The makefile.*'s are not set up for cross-build use.
#
# The naming used does require (relative to POSIX):
# "allow other characters in target names as extensions"
#

#
# This file presumes FreeBSD port devel/llvm17 is installed.
#

# Note: As of main_n263893_0631830a7a3c the system libc++ is
#       presumed to be from LLVM 16 or later, no longer
#       from LLVM 15. This is used to avoid async's policy
#       control for thread managment. (devel/llvm* do not
#       have their own libc++'s but use the system one
#       instead.)
#

CXXLIB=
CXX=            clang++17 -v -std=c++23 -Wpedantic -Wall -Wextra
#CXX+=           -stdlib=libc++
#CXX+=           -Wno-psabi -nostdinc -nostdinc++ -I/usr/include/c++/v1 -I/usr/include
#CXX+=           -DDSIZE_ALL_ISIZE_ALL
OPT=            -O3
LTO_STYLE=      -flto
OPT+=           ${LTO_STYLE}
CPULOCKDOWN_OPT=
#CPULOCKDOWN_OPT=        -DWANT_CPU_LOCKDOWN
# Note for FreeBSD: WANT_NUMA_TOO is implicit/automatic; not so for Linux
#CPULOCKDOWN_OPT+=       -DWANT_NUMA_TOO
#LDCXX=          -nodefaultlibs -lc++ -lcxxrt -lthr -lm -lc -lgcc_s
LDCXX+=         -fuse-ld=lld ${LTO_STYLE}
# For Linux NUMA use:
#LDCXX+=         -lnuma

COMPILER_DESC=      clang++_17_O3lto
LIBRARY_DESC=       libc++
COMPILER_LIBRARY=   ${COMPILER_DESC}-${LIBRARY_DESC}

COMPUTER=               7950X3D
RAM=                    98304MiB
THREADS=                threads_32
CPP_DATA_MODEL=         LP64
OS=                     FreeBSD_main_n266130_d521abdff236_64bit
SUFFIX=
#SUFFIX=                 -cpulockdown
ACPPHINT_FILENAME_INFO= ${COMPUTER}-${RAM}-${THREADS}-${CPP_DATA_MODEL}-${OS}-${COMPILER_LIBRARY}${SUFFIX}
#
# Note: The "threads_32" is what the hardware has for
# HW threads --or as presented by the likes of HyperV.
# acpphint will also add using_N_threads to file names
# recording benchmark results.

include makefile.common_part

#
#  Support some special NOPREFER-related information gathering:
#
gather-NOPREFER-info: \
		cpp_clockinfo_main-run \
		acpphint_kernelsurveyors_main-run \
		acpphint_kernelsamplers_main-run \
		acpphint-NOPREFER-run

acpphint-NOPREFER-run:
	cd .. && cpuset -l0,1                                        ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_1.txt"                   2
	cd .. && cpuset -l0,2                                        ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_2.txt"                   2
	cd .. && cpuset -l0,4                                        ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_4.txt"                   2
	cd .. && cpuset -l0,8                                        ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_8.txt"                   2
	cd .. && cpuset -l0,16                                       ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_0_16.txt"                  2
	cd .. && cpuset -l0,1,4,5                                    ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_kx4_kx4p1_0_5.txt"         4
	cd .. && cpuset -l0,2,4,6                                    ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_kx2s_0_6.txt"              4
	cd .. && cpuset -l0,1,8,9                                    ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_kx4_kx4p1_0_9.txt"         4
	cd .. && cpuset -l0,2,8,10                                   ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_kx8_kx8p2_0_2_8_10.txt"    4
	cd .. && cpuset -l0,1,16,17                                  ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_kx16_kx16p1_0_1_16_17.txt" 4
	cd .. && cpuset -l0,2,16,18                                  ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_kx16_kx16p2_0_2_16_18.txt" 4
	cd .. && cpuset -l0,4,8,12                                   ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_kx4s_0_12.txt"             4
	cd .. && cpuset -l0,4,16,20                                  ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_kx16_kx16p4_0_4_16_20.txt" 4
	cd .. && cpuset -l0,8,16,24                                  ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_kx8s_0_24.txt"             4
	cd .. && cpuset -l0,1,4,5,8,9,12,13                          ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_kx4_kx4p1_0_13.txt"        8
	cd .. && cpuset -l0,2,4,6,8,10,12,14                         ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_kx2s_0_14.txt"             8
	cd .. && cpuset -l0,1,4,5,16,17,20,21                        ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_kx4_kx4p1_0_5_16_21.txt"   8
	cd .. && cpuset -l0,2,4,6,16,18,20,22                        ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_kx2s_0_6_16_22.txt"        8
	cd .. && cpuset -l0,4,8,12,16,20,24,28                       ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_kx4s_0_28.txt"             8
	cd .. && cpuset -l0,1,4,5,8,9,12,13,16,17,20,21,24,25,28,29  ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_kx4_kx4p1_0_29.txt"        16
	cd .. && cpuset -l0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30 ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} "-cpus_kx2s_0_30.txt"             16
	cd .. && ./${@:-NOPREFER-run=}-${ACPPHINT_FILENAME_INFO} ".txt" 2

#
#  Support some NUMA-related information gathering:
#
gather-NUMA-info: \
		cpp_clockinfo_main-run \
		acpphint_kernelsurveyors_main-run \
		acpphint_kernelsamplers_main-run \
		acpphint-NUMA-run
                
acpphint-NUMA-run:
	cd .. && cpuset -l0,4,8,12                                   -n prefer:0 ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-prefer_0_cpus_kx4s_0_12.txt"      4
	cd .. && cpuset -l0,4,8,12                                   -n prefer:1 ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-prefer_1_cpus_kx4s_0_12.txt"      4
	cd .. && cpuset -l0,4,8,12                                   -n rr:0,1   ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-rr_0_1_cpus_kx4s_0_12.txt"        4
	cd .. && cpuset -l0,4,8,12                                   -n il:0,1   ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-il_0_1_cpus_kx4s_0_12.txt"        4
	cd .. && cpuset -l0,4,16,20                                  -n prefer:0 ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-prefer_0_cpus_kx4s_0_4_16_20.txt" 4
	cd .. && cpuset -l0,4,16,20                                  -n prefer:1 ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-prefer_1_cpus_kx4s_0_4_16_20.txt" 4
	cd .. && cpuset -l0,4,16,20                                  -n rr:0,1   ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-rr_0_1_cpus_kx4s_0_4_16_20.txt"   4
	cd .. && cpuset -l0,4,16,20                                  -n il:0,1   ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-il_0_1_cpus_kx4s_0_4_16_20.txt"   4
	cd .. && cpuset -l0,8,16,24                                  -n prefer:0 ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-prefer_0_cpus_kx8s_0_24.txt"      4
	cd .. && cpuset -l0,8,16,24                                  -n prefer:1 ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-prefer_1_cpus_kx8s_0_24.txt"      4
	cd .. && cpuset -l0,8,16,24                                  -n rr:0,1   ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-rr_0_1_cpus_kx8s_0_24.txt"        4
	cd .. && cpuset -l0,8,16,24                                  -n il:0,1   ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-il_0_1_cpus_kx8s_0_24.txt"        4
	cd .. && cpuset -l0,2,4,6,8,10,12,14                         -n prefer:0 ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-prefer_0_cpus_kx2s_0_14.txt"      8
	cd .. && cpuset -l0,2,4,6,8,10,12,14                         -n prefer:1 ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-prefer_1_cpus_kx2s_0_14.txt"      8
	cd .. && cpuset -l0,2,4,6,8,10,12,14                         -n rr:0,1   ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-rr_0_1_cpus_kx2s_0_14.txt"        8
	cd .. && cpuset -l0,2,4,6,8,10,12,14                         -n il:0,1   ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-il_0_1_cpus_kx2s_0_14.txt"        8
	cd .. && cpuset -l0,2,4,6,16,18,20,22                        -n prefer:0 ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-prefer_0_cpus_kx2s_0_6_16_22.txt" 8
	cd .. && cpuset -l0,2,4,6,16,18,20,22                        -n prefer:1 ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-prefer_1_cpus_kx2s_0_6_16_22.txt" 8
	cd .. && cpuset -l0,2,4,6,16,18,20,22                        -n rr:0,1   ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-rr_0_1_cpus_kx2s_0_6_16_22.txt"   8
	cd .. && cpuset -l0,2,4,6,16,18,20,22                        -n il:0,1   ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-il_0_1_cpus_kx2s_0_6_16_22.txt"   8
	cd .. && cpuset -l0,4,8,12,16,20,24,28                       -n prefer:0 ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-prefer_0_cpus_kx4s_0_28.txt"      8
	cd .. && cpuset -l0,4,8,12,16,20,24,28                       -n prefer:1 ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-prefer_1_cpus_kx4s_0_28.txt"      8
	cd .. && cpuset -l0,4,8,12,16,20,24,28                       -n rr:0,1   ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-rr_0_1_cpus_kx4s_0_28.txt"        8
	cd .. && cpuset -l0,4,8,12,16,20,24,28                       -n il:0,1   ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-il_0_1_cpus_kx4s_0_28.txt"        8
	cd .. && cpuset -l0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30 -n prefer:0 ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-prefer_0_cpus_kx2s_0_30.txt"      16
	cd .. && cpuset -l0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30 -n prefer:1 ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-prefer_1_cpus_kx2s_0_30.txt"      16
	cd .. && cpuset -l0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30 -n rr:0,1   ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-rr_0_1_cpus_kx2s_0_30.txt"        16
	cd .. && cpuset -l0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30 -n il:0,1   ./${@:-NUMA-run=}-${ACPPHINT_FILENAME_INFO} "-il_0_1_cpus_kx2s_0_30.txt"        16
